language: node_js
node_js:
  - "8"

install:
  - npm install

before_script:
  - npm test

script:
  - npm run build

deploy:
  skip_cleanup: true

notifications:
  email:
    recipients:
      - jakub.dakowicz@pagepro.pl
    on_success: never # default: change
    on_failure: always # default: always